import {
  AlarmSmoke,
  Anchor,
  Armchair,
  Bath,
  BedDouble,
  Coffee,
  CookingPot,
  Droplets,
  Flame,
  Gamepad2,
  Heater,
  PawPrint,
  Refrigerator,
  Sailboat,
  Shirt,
  Snowflake,
  SquareParking,
  Sun,
  Tv,
  Users,
  Utensils,
  WashingMachine,
  Waves,
  Wifi,
  Wind,
  type LucideIcon,
} from "lucide-react";
import type { AmenityIcon } from "@/lib/property";

export const AMENITY_ICONS: Record<AmenityIcon, LucideIcon> = {
  water: Sailboat,
  "hot-tub": Waves,
  outdoor: Sun,
  fire: Flame,
  games: Gamepad2,
  bed: BedDouble,
  kitchen: CookingPot,
  laundry: WashingMachine,
  guests: Users,
  pets: PawPrint,
  wifi: Wifi,
  ac: Snowflake,
  heating: Heater,
  "hot-water": Droplets,
  tv: Tv,
  fridge: Refrigerator,
  cooking: Utensils,
  coffee: Coffee,
  clothes: Shirt,
  "hair-dryer": Wind,
  essentials: Bath,
  furniture: Armchair,
  waterfront: Anchor,
  parking: SquareParking,
  "smoke-alarm": AlarmSmoke,
};
